language : node_js
node_js : 
  - "8.10.0"

before_install:
  - npm i g npm@5.6.0

before_script:
- npm install

script:
- npm run build

before_deploy:
  - openssl aes-256-cbc -K $encrypted_003266033f1b_key -iv $encrypted_003266033f1b_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d 
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

deploy:
  - provider: script
    script:
       bash ./deploy.sh

addons:
  ssh_known_hosts:
  - utest.eastus.cloudapp.azure.com



