language : node_js
node_js : 
  - "8.10.0"

before_install:
  - npm i g npm@5.6.0

before_script:
- npm install

before_deploy:
  - chmod 600 ./id_rsa

deploy:
  - provider: script
    script:
       bash ./deploy.sh

script:
- npm run build

addons:
  ssh_known_hosts:
  - utest.eastus.cloudapp.azure.com