language: node_js
node_js:
- 6.11.4
before_install:
- npm i g npm@3.5.2
before_script:
- npm install
script:
- npm run build

before_deploy:
- openssl aes-256-cbc -K $encrypted_7a37f05d513a_key -iv $encrypted_7a37f05d513a_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

deploy:
- provider: script
  skip_cleanup: true
  script: scp -C  -r  ./build/* taung@utest.eastus.cloudapp.azure.com:/var/www/html

addons:
  ssh_known_hosts:
  - utest.eastus.cloudapp.azure.com

cache: 
directories:
  - node_modules